### PR TITLE
Expose `common.h` llama.cpp Header

### PR DESCRIPTION
**Pull request by philippzagar**
# Expose `common.h` llama.cpp Header

## :recycle: Current situation & Problem
As of now, the `llama.cpp` SPM package as well as our compiled XCFramework version do not expose the `common.h` headers which offer additional functionality to the library user. The `common.h` headers are used extensively in the Server-component of `llama.cpp`  as well as other wrapper implementations building on top of `llama.cpp`. I'm actually not really sure why the authors of `llama.cpp` don't expose this header by default by now (they have lots of TODOs in the `common.h` file outlining the move of some functions / structs to the `llama.h` public API).

## :gear: Release Notes 
- The `llama.cpp` XCFramework binary now exposes the `common.h` header

## :books: Documentation
--

## :white_check_mark: Testing
Manually tested

### Code of Conduct & Contributing Guidelines 

By submitting creating this pull request, you agree to follow our [Code of Conduct](https://github.com/StanfordBDHG/.github/blob/main/CODE_OF_CONDUCT.md) and [Contributing Guidelines](https://github.com/StanfordBDHG/.github/blob/main/CONTRIBUTING.md):
- [X] I agree to follow the [Code of Conduct](https://github.com/StanfordBDHG/.github/blob/main/CODE_OF_CONDUCT.md) and [Contributing Guidelines](https://github.com/StanfordBDHG/.github/blob/main/CONTRIBUTING.md).

### CODE REVIEW

**Comment by philippzagar** [comment]
~~@PSchmiedmayer Would be great to merge this quickly so that I don't need to depend on a local XCFramework binary :)~~
Nevermind that, I noticed a couple more things that I'll probably move into this PR.

**Review by PSchmiedmayer — APPROVED** [review]
Looks good to me, thank you @philippzagar for the work on the project 🚀

**Comment by philippzagar** [comment]
@PSchmiedmayer PR should be ready for a second brief review. I merged all the changes from upstream into this branch (couldn't sync directly as one merge conflict occurred), therefore the quite big diff.
Regarding the license files: Is it correct the way I did in the PR? According to [this](https://opensource.stackexchange.com/questions/7916/should-i-use-my-own-license-in-a-fork-of-another-github-repository-which-ive-r), one needs to leave the original license files + copyrights in there

**Review by PSchmiedmayer — APPROVED** [review]
@philippzagar Thank you for all the improvements!

Yes, keeping the license there is the way to go. We should also mention this in the "License" section in the README that this is a fork of an MIT licensed project and we keep all changes under the MIT license. Apart from this I think that the overall changes and the focus on the README on the Swift usage makes sense. I would just suggest to maybe add a `NOTE` or something similar to link people to the other README in case they have further questions about the code base.

**Comment by philippzagar** [comment]
@PSchmiedmayer Thanks for the feedback, incorporated it! Will merge this PR now

**Pull request merged**
